//
// Created by piotr on 20/04/16.
//

#ifndef VANILLACNN_CLION_INTERNALLYWEIGHTEDNEURONSFACTORY_H
#define VANILLACNN_CLION_INTERNALLYWEIGHTEDNEURONSFACTORY_H


class InternallyWeightedNeuronsFactory {

};


#endif //VANILLACNN_CLION_INTERNALLYWEIGHTEDNEURONSFACTORY_H
