//
// Created by piotr on 20/04/17.
//

#ifndef VANILLACNN_CLION_IWEIGHTLESSCONTAINER_H
#define VANILLACNN_CLION_IWEIGHTLESSCONTAINER_H


class IWeightlessContainer {

};


#endif //VANILLACNN_CLION_IWEIGHTLESSCONTAINER_H
