//
// Created by piotr on 20/04/16.
//

#ifndef VANILLACNN_CLION_INTERNALLYWEIGHTEDNEURON_H
#define VANILLACNN_CLION_INTERNALLYWEIGHTEDNEURON_H


class InternallyWeightedNeuron {

};


#endif //VANILLACNN_CLION_INTERNALLYWEIGHTEDNEURON_H
